apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-configmap
  namespace: project
data:
  PORT: "6000"
  DB_HOST: "postgres-svc"
  # TODO: store password in a Secret
  DB_PASSWORD: example
