apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
- ../../../../../shared/nats/prod
images:
- name: PROJECT/IMAGE
  newName: k8slabscontainerregistry.azurecr.io/todo-backend
  newTag: d678e20893a5e1d043d21692137032016066759c
namespace: prod
