apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-folder
          persistentVolumeClaim:
            claimName: log-output-pv-claim
        - name: information
          configMap:
            name: log-output-configmap
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: log-webapp
          image: jpvalencia/log-webapp:07f3866e8d78
          volumeMounts:
            - name: shared-folder
              mountPath: /usr/src/app/files
            - name: information
              mountPath: /information
              readOnly: true
          env:
            - name: PORT
              value: "3000"
            - name: PING_PONG_SVC_URL
              value: "http://ping-pong-svc:3456"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: message
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /ready
               port: 3000
        - name: string-generator
          image: jpvalencia/string-generator:3cd81820d22e
          volumeMounts:
            - name: shared-folder
              mountPath: /usr/src/app/files
