apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-folder
          persistentVolumeClaim:
            claimName: log-output-claim
      containers:
        - name: log-webapp
          image: jpvalencia/log-webapp:e8c3ba8d74a7
          volumeMounts:
          - name: shared-folder
            mountPath: /usr/src/app/files
        - name: string-generator
          image: jpvalencia/string-generator:09e1504ed695
          volumeMounts:
          - name: shared-folder
            mountPath: /usr/src/app/files
