apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-folder
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
        - name: log-webapp
          image: jpvalencia/log-webapp:e1f5616cd4a5
          volumeMounts:
            - name: shared-folder
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3000"
            - name: PING_PONG_SVC_URL
              value: "http://ping-pong-svc:3456"
        - name: string-generator
          image: jpvalencia/string-generator:09e1504ed695
          volumeMounts:
            - name: shared-folder
              mountPath: /usr/src/app/files
