apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-output-pv-claim
  namespace: exercises
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
