apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
images:
- name: PROJECT/IMAGE
  newName: k8slabscontainerregistry.azurecr.io/todo-app
  newTag: 2c8eeac902b8523df2ad7db64027a8394f82482d
namespace: staging
