apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  strategy: # TODO: fix volume multi-attach problem to avoid using Recreate
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-folder
          persistentVolumeClaim:
            claimName: todo-app-pv-claim
      containers:
        - name: todo-app
          image: PROJECT/IMAGE
          volumeMounts:
          - name: shared-folder
            mountPath: /usr/src/app/files
          envFrom:
            - configMapRef:
                name: todo-app-configmap
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "150m"
              memory: "250Mi"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /ready
               port: 5000
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 5000
