apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-folder
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
        - name: todo-app
          image: jpvalencia/todo-app:7803adad2ecb
          volumeMounts:
          - name: shared-folder
            mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "5000"
