apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-folder
          persistentVolumeClaim:
            claimName: todo-app-pv-claim
      containers:
        - name: todo-app
          image: jpvalencia/todo-app:74f822f87738
          volumeMounts:
          - name: shared-folder
            mountPath: /usr/src/app/files
          envFrom:
            - configMapRef:
                name: todo-app-configmap
