apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      volumes:
        - name: shared-folder
          persistentVolumeClaim:
            claimName: broadcaster-pv-claim
      containers:
        - name: broadcaster
          image: PROJECT/IMAGE
          volumeMounts:
          - name: shared-folder
            mountPath: /usr/src/app/files
          envFrom:
            - configMapRef:
                name: broadcaster-configmap
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "150m"
              memory: "250Mi"
