apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - namespace.yaml
images:
  - name: PROJECT/IMAGE
    newName: jpvalencia/broadcaster:1c5b117f4756
