apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-reminder-job
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-reminder
            image: jpvalencia/todo-reminder-job:c6adc105a937
            env:
            - name: TODO_BACKEND_URL
              value: http://todo-backend-svc:4567
          restartPolicy: Never
