apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: PROJECT/IMAGE
  newName: k8slabscontainerregistry.azurecr.io/todo-app
  newTag: 89d5f32567e60353c646d08d0ab503e29676e9bc
