apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../../../shared/nats
images:
- name: PROJECT/IMAGE
  newName: k8slabscontainerregistry.azurecr.io/broadcaster
  newTag: 20b2c4acfb63b99ed037ab712797b15f96d26a07
namespace: project
