apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- pv-claim.yaml
images:
- name: PROJECT/IMAGE
  newName: k8slabscontainerregistry.azurecr.io/broadcaster
  newTag: a130f91a8cad328a2f459a52126d42ad3f435d9b
